name: PDF_Flow
description: "A base app"
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8 

  flutter_keyboard_visibility: 6.0.0
  flutter_screenutil: 5.9.1
  collection: 1.19.1
  flutter_svg: 2.1.0
  lottie: 3.3.1

  smooth_page_indicator: 1.2.1
  intl: any
  shared_preferences: 2.5.3
  in_app_review: 2.0.10
  provider: 6.1.5
  uuid: 4.5.1
  package_info_plus: 8.3.0
  share_plus: 11.0.0
  path_provider: 2.1.5
  apphud_helper:
    git:
      url: git@github.com:AppEmpireSwift/apphud_helper.git
      ref: 0.3.1
  new_version_plus: 0.1.0

  device_preview_plus: ^2.3.5

dependency_overrides:
  device_frame_plus: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0

  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/lottie/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/premium/
